fix: use eval instead of require
In most ENB packages used `mock-fs` to testing.

The `mock-fs` does not support `require` for `Node.js 4`: https://github.com/tschaub/mock-fs/issues/43.

Because of this `node.runTechAndRequire()` will throw error:

```
Cannot find module 'path/to/file.js'
```